### ISSUE TITLE
Use example script in root rather than putting test in main

### ISSUE THREAD

**Issue by ErikBoesen** [LucasHaefner/StrFry#10]
It's fine and healthy to have example code in your repo using the package, but it doesn't make sense to include it in your `table.py` since you shouldn't be running that directly and it's not quite realistic. Instead, add an `example.py` file (or similar) to the project root that just does `import strfry` (it will default to importing from the directory rather than the package) and uses it there. That way it won't get packaged in with the actual functional code of the package.

**Comment by LucasHaefner** [comment]
thx this is soo helpful
