### ISSUE TITLE
Note: commit title standards

### ISSUE THREAD

**Issue by ErikBoesen** [LucasHaefner/StrFry#11]
Some standards to follow for writing commit titles. This is not a huge deal unless you're on a corporate team but just good practice to think about going forward:
- Be descriptive. `Update table.py` is not clear because I don't know what you actually updated. A better name might be `Improve spacing in table.py`.
- Split up commits when in doubt. To use that commit as an example, you could have split it into two commits, i.e. `Improve spacing in table.py` and `Remove comment in table.py` or something. This is kind of a matter of preference but I typically lean towards one comment per change that you can put a name to. This makes it easier to understand the commit history.
- Use the *imperative tense* in your commit titles, rather than past tense or anything else. So for example, say `Add something` rather than `Added something` or `Adds something`. This matches git's standard (i.e. "Merge branch example into anotherexample" and similar messages). If in doubt, to know if a commit is in the proper tense you can think of whether it would fit in to the sentence "When applied, this commit will ______".

There are a bunch more tips on this article: https://chris.beams.io/posts/git-commit/

**Comment by LucasHaefner** [comment]
Good to know.
